version: 2.1

jobs:
  run_build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Run Black
          command: |
            sudo pip install black
            black --check .

  remove_branchless_stacks:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
              pip install --user -r clean_up_cf/requirements.txt
      - run:
          name: Clean Up Cloudformation
          command:
              python clean_up_cf/remove_branchless_stacks.py "alasco-tech/alasco-app" --region "eu-central-1"

workflows:
  build_and_test:
    jobs:
      - run_build

  clean_up_cloudformation:
    triggers:
      - schedule:
          cron: "30 * * * *"
          filters:
            branches:
              only:
              - master
    jobs:
      - remove_branchless_stacks:
          context: cf_clean_up
